export const RACE_TRACKS = {
    "MBC": "Mario Bros. Circuit",
    "CC": "Crown City",
    "WS": "Whistlestop Summit",
    "DSS": "DK Spaceport",
    "DH": "Desert Hills",
    "SGB": "Shy Guy Bazaar",
    "WS2": "Wario Stadium",
    "AF": "Airship Fortress",
    "DP": "DK Pass",
    "SVP": "Starview Peak",
    "SHS": "Sky-High Sundae",
    "WSY": "Wario Shipyard",
    "KTB": "Koopa Troopa Beach",
    "FO": "Faraway Oasis",
    "PS": "Peach Stadium",
    "PB": "Peach Beach",
    "SSS": "Salty Salty Speedway",
    "DDJ": "Dino Dino Jungle",
    "GBR": "Great ? Block Ruins",
    "CCF": "Cheep Cheep Falls",
    "DD": "Dandelion Depths",
    "BC": "Boo Cinema",
    "DBB": "Dry Bones Burnout",
    "MMM": "Moo Moo Meadows",
    "CM": "Choco Mountain",
    "TF": "Toad's Factory",
    "BCASTLE": "Bowser's Castle",
    "AH": "Acorn Heights",
    "MC": "Mario Circuit",
    "RR": "Rainbow Road",
} as const;
